import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface AnalyticsData {
    cropName: string;
    data: Array<{
        month: string;
        price: number;
    }>;
}

export function exportAnalyticsToPDF(
    analyticsData: AnalyticsData,
    farmerName: string = 'Farmer'
): void {
    const doc = new jsPDF();

    // Add header
    doc.setFontSize(20);
    doc.setTextColor(34, 197, 94); // Primary green color
    doc.text('KrishiMitraAI', 14, 22);

    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text('Market Price Analytics Report', 14, 32);

    // Add metadata
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated for: ${farmerName}`, 14, 42);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 48);
    doc.text(`Crop: ${analyticsData.cropName}`, 14, 54);

    // Add table
    const tableData = analyticsData.data.map(item => [
        item.month,
        `₹${item.price}/kg`
    ]);

    autoTable(doc, {
        startY: 62,
        head: [['Month', 'Price']],
        body: tableData,
        theme: 'grid',
        headStyles: {
            fillColor: [34, 197, 94],
            textColor: [255, 255, 255],
            fontSize: 11,
            fontStyle: 'bold'
        },
        bodyStyles: {
            fontSize: 10
        },
        alternateRowStyles: {
            fillColor: [245, 245, 245]
        }
    });

    // Calculate statistics
    const prices = analyticsData.data.map(d => d.price);
    const avgPrice = prices.reduce((a, b) => a + b, 0) / prices.length;
    const maxPrice = Math.max(...prices);
    const minPrice = Math.min(...prices);

    // Add statistics
    const finalY = (doc as any).lastAutoTable.finalY || 62;

    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text('Price Statistics', 14, finalY + 15);

    doc.setFontSize(10);
    doc.text(`Average Price: ₹${avgPrice.toFixed(2)}/kg`, 14, finalY + 23);
    doc.text(`Highest Price: ₹${maxPrice}/kg`, 14, finalY + 30);
    doc.text(`Lowest Price: ₹${minPrice}/kg`, 14, finalY + 37);

    // Add footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
        'Generated by KrishiMitraAI - Smart Agriculture Platform',
        14,
        doc.internal.pageSize.height - 10
    );

    // Save the PDF
    doc.save(`${analyticsData.cropName}_Analytics_${new Date().toISOString().split('T')[0]}.pdf`);
}

export interface FarmReport {
    farmerName: string;
    farmSize: string;
    location: string;
    crops: Array<{
        name: string;
        area: string;
        yield: string;
        profit: string;
    }>;
    totalRevenue: number;
    totalExpenses: number;
    netProfit: number;
}

export function exportFarmReportToPDF(report: FarmReport): void {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(22);
    doc.setTextColor(34, 197, 94);
    doc.text('KrishiMitraAI', 14, 22);

    doc.setFontSize(18);
    doc.setTextColor(0, 0, 0);
    doc.text('Farm Management Report', 14, 34);

    // Farmer Details
    doc.setFontSize(12);
    doc.setTextColor(60, 60, 60);
    doc.text(`Farmer: ${report.farmerName}`, 14, 46);
    doc.text(`Farm Size: ${report.farmSize}`, 14, 53);
    doc.text(`Location: ${report.location}`, 14, 60);
    doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 14, 67);

    // Crops Table
    const cropData = report.crops.map(crop => [
        crop.name,
        crop.area,
        crop.yield,
        crop.profit
    ]);

    autoTable(doc, {
        startY: 75,
        head: [['Crop', 'Area', 'Yield', 'Profit']],
        body: cropData,
        theme: 'striped',
        headStyles: {
            fillColor: [34, 197, 94],
            fontSize: 11
        }
    });

    // Financial Summary
    const finalY = (doc as any).lastAutoTable.finalY || 75;

    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Financial Summary', 14, finalY + 15);

    doc.setFontSize(11);
    doc.text(`Total Revenue: ₹${report.totalRevenue.toLocaleString()}`, 14, finalY + 25);
    doc.text(`Total Expenses: ₹${report.totalExpenses.toLocaleString()}`, 14, finalY + 32);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    const profitColor: [number, number, number] = report.netProfit >= 0 ? [34, 197, 94] : [239, 68, 68];
    doc.setTextColor(profitColor[0], profitColor[1], profitColor[2]);
    doc.text(`Net Profit: ₹${report.netProfit.toLocaleString()}`, 14, finalY + 42);

    // Footer
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
        'This report is generated by KrishiMitraAI for informational purposes',
        14,
        doc.internal.pageSize.height - 10
    );

    doc.save(`Farm_Report_${report.farmerName}_${new Date().toISOString().split('T')[0]}.pdf`);
}
